### ISSUE TITLE
KeyError:  ?

### ISSUE THREAD

**Issue by liushuqing506** [zjshi/Maast#20]
'''
1398/GCA_017353475.1_ASM1735347v1_genomic.fna
Running mummer4; start
reference genome path: 1398/GCA_017353475.1_ASM1735347v1_genomic.fna
[paired alignment]: start
[paired alignment]: done
	GCA_017353475.1_ASM1735347v1_genomic - GCA_021764685.1_ASM2176468v1_genomic
	GCA_017353475.1_ASM1735347v1_genomic - GCA_003184245.1_ASM318424v1_genomic
	GCA_017353475.1_ASM1735347v1_genomic - GCA_017353475.1_ASM1735347v1_genomic
	GCA_017353475.1_ASM1735347v1_genomic - GCA_000482605.1_ASM48260v1_genomic
	GCA_017353475.1_ASM1735347v1_genomic - GCA_902796085.1_Rumen_uncultured_genome_RUG14133_genomic
	GCA_017353475.1_ASM1735347v1_genomic - GCA_026104335.1_ASM2610433v1_genomic
Reading reference genome
   count contigs: 82
   count sites: 3060890
Initializing alignments
   count genomes: 13
Reading alignment blocks
Traceback (most recent call last):
  File "/home/liusq/miniconda3/envs/maast/share/maast-1.0.8-0/bin/maast.py", line 1395, in <module>
    main()
  File "/home/liusq/miniconda3/envs/maast/share/maast-1.0.8-0/bin/maast.py", line 1382, in main
    call_snps_main(args)
  File "/home/liusq/miniconda3/envs/maast/share/maast-1.0.8-0/bin/maast.py", line 1187, in call_snps_main
    run_mummer4(args)
  File "/home/liusq/miniconda3/envs/maast/share/maast-1.0.8-0/bin/maast.py", line 516, in run_mummer4
    msa_path = gen_msa.build_msa(indir=args['mummer4_dir'], overwrite=True, subset=args["subset_map"])
  File "/home/liusq/miniconda3/envs/maast/share/maast-1.0.8-0/snps_io/gen_msa.py", line 97, in build_msa
    genomes[genome_id][r['c1']][r['s1']-1:r['e1']] = ref[r['c1']][r['s1']-1:r['e1']]
KeyError: 'CP110483.1'
'''

**Comment by zjshi** [comment]
Hi liushuqing506, thanks for trying maast. Could you please let me know how you ran your analysis?
